# Generated by Django 2.1.3 on 2019-07-11 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this particular Playlist across entire site', primary_key=True, serialize=False)),
                ('playlist_creation_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('playlist_name', models.CharField(help_text='Enter a title for the playlist', max_length=128)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('access_token', models.CharField(max_length=128)),
                ('refresh_token', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this particular Song across entire site', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('artist', models.CharField(max_length=128)),
                ('length', models.CharField(max_length=128)),
                ('preview_link', models.CharField(max_length=128)),
                ('genre', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='SongInstance',
            fields=[
                ('song_instance_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this particular Song Instance', primary_key=True, serialize=False)),
                ('number_yes_votes', models.IntegerField(default=0)),
                ('number_no_votes', models.IntegerField(default=0)),
                ('adder_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('playlist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Playlist')),
                ('song_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Song')),
            ],
        ),
        migrations.AddField(
            model_name='contributors',
            name='playlist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Playlist'),
        ),
    ]
